import type { Locale } from "@/lib/i18n";
import type { Allergen, Badge, Highlight } from "@/lib/types";

export type Plan = "freemium" | "premium" | "elite";
export type Template = "liste" | "grid";

export const allergenLabels: Record<Locale, Record<Allergen, string>> = {
  tr: {
    gluten: "Gluten",
    laktoz: "Laktoz",
    yumurta: "Yumurta",
    findik_fistik: "Fındık/Fıstık",
    yer_fistigi: "Yer fıstığı",
    soya: "Soya",
    balik: "Balık",
    kabuklu_deniz_urunu: "Kabuklu deniz ürünü",
    susam: "Susam",
    hardal: "Hardal",
    kereviz: "Kereviz",
    sulfit: "Sülfit",
  },
  en: {
    gluten: "Gluten",
    laktoz: "Lactose",
    yumurta: "Egg",
    findik_fistik: "Nuts",
    yer_fistigi: "Peanut",
    soya: "Soy",
    balik: "Fish",
    kabuklu_deniz_urunu: "Shellfish",
    susam: "Sesame",
    hardal: "Mustard",
    kereviz: "Celery",
    sulfit: "Sulphites",
  },
  ar: {
    gluten: "الغلوتين",
    laktoz: "اللاكتوز",
    yumurta: "البيض",
    findik_fistik: "المكسرات",
    yer_fistigi: "الفول السوداني",
    soya: "الصويا",
    balik: "السمك",
    kabuklu_deniz_urunu: "المحار",
    susam: "السمسم",
    hardal: "الخردل",
    kereviz: "الكرفس",
    sulfit: "الكبريتيت",
  },
  ru: {
    gluten: "Глютен",
    laktoz: "Лактоза",
    yumurta: "Яйцо",
    findik_fistik: "Орехи",
    yer_fistigi: "Арахис",
    soya: "Соя",
    balik: "Рыба",
    kabuklu_deniz_urunu: "Моллюски",
    susam: "Кунжут",
    hardal: "Горчица",
    kereviz: "Сельдерей",
    sulfit: "Сульфиты",
  },
};

export const badgeLabels: Record<Locale, Record<Badge, string>> = {
  tr: {
    yeni: "Yeni",
    sefin_onerisi: "Şefin önerisi",
    populer: "Popüler",
    vejetaryen: "Vejetaryen",
    vegan: "Vegan",
    aci: "Acılı",
    glutensiz: "Glutensiz",
  },
  en: {
    yeni: "New",
    sefin_onerisi: "Chef's pick",
    populer: "Popular",
    vejetaryen: "Vegetarian",
    vegan: "Vegan",
    aci: "Spicy",
    glutensiz: "Gluten-free",
  },
  ar: {
    yeni: "جديد",
    sefin_onerisi: "توصية الشيف",
    populer: "الأكثر طلبًا",
    vejetaryen: "نباتي",
    vegan: "نباتي صرف",
    aci: "حار",
    glutensiz: "خالٍ من الغلوتين",
  },
  ru: {
    yeni: "Новинка",
    sefin_onerisi: "Выбор шефа",
    populer: "Популярное",
    vejetaryen: "Вегетарианское",
    vegan: "Веганское",
    aci: "Острое",
    glutensiz: "Без глютена",
  },
};

export const highlightLabels: Record<Locale, Record<Highlight, string>> = {
  tr: {
    wifi: "Ücretsiz Wi-Fi",
    vale: "Vale Hizmeti",
    otopark: "Otopark",
    cocuk_oyun_alani: "Çocuk Oyun Alanı",
    evcil_hayvan_dostu: "Evcil Hayvan Dostu",
    teras: "Teras",
    canli_muzik: "Canlı Müzik",
    rezervasyon: "Rezervasyon",
    kredi_karti: "Kredi Kartı",
    engelli_erisimi: "Engelli Erişimi",
    sigara_alani: "Sigara Alanı",
    kahvalti: "Kahvaltı",
  },
  en: {
    wifi: "Free Wi-Fi",
    vale: "Valet Service",
    otopark: "Parking",
    cocuk_oyun_alani: "Kids' Play Area",
    evcil_hayvan_dostu: "Pet Friendly",
    teras: "Terrace",
    canli_muzik: "Live Music",
    rezervasyon: "Reservations",
    kredi_karti: "Credit Card",
    engelli_erisimi: "Accessible",
    sigara_alani: "Smoking Area",
    kahvalti: "Breakfast",
  },
  ar: {
    wifi: "واي فاي مجاني",
    vale: "خدمة صف السيارات",
    otopark: "موقف سيارات",
    cocuk_oyun_alani: "منطقة ألعاب أطفال",
    evcil_hayvan_dostu: "يسمح بالحيوانات الأليفة",
    teras: "تراس",
    canli_muzik: "موسيقى حية",
    rezervasyon: "حجز مسبق",
    kredi_karti: "بطاقة ائتمان",
    engelli_erisimi: "دخول لذوي الاحتياجات",
    sigara_alani: "منطقة تدخين",
    kahvalti: "إفطار",
  },
  ru: {
    wifi: "Бесплатный Wi-Fi",
    vale: "Услуги парковщика",
    otopark: "Парковка",
    cocuk_oyun_alani: "Детская площадка",
    evcil_hayvan_dostu: "Можно с животными",
    teras: "Терраса",
    canli_muzik: "Живая музыка",
    rezervasyon: "Бронирование",
    kredi_karti: "Оплата картой",
    engelli_erisimi: "Доступная среда",
    sigara_alani: "Зона для курения",
    kahvalti: "Завтрак",
  },
};

export const planLabels: Record<Plan, string> = {
  freemium: "Freemium",
  premium: "Premium",
  elite: "Elite",
};
